export const ADD_AVAILABLE = 'ADD_AVAILABLE';
export const ADD_SELF = 'ADD_SELF';
export const ADD_UNAVAILABLE = 'ADD_UNAVAILABLE';
export const REMOVE_AVAILABLE = 'REMOVE_AVAILABLE';
export const REMOVE_SELF = 'REMOVE_SELF';
export const REMOVE_UNAVAILABLE = 'REMOVE_UNAVAILABLE';
